---
title: "Body weight follow up"
author: "OG"
date: "8/15/2020"
output: html_document
---

```{r setup, include=T, echo= F}
knitr::opts_chunk$set(echo = F, eval = T)
library(tidyverse, quietly = T)
library(lubridate, quietly = T)
# loads data from export file in Download folder and creates rds file
source("R/appleHealthDataXMLimport.R")
theme_set(theme_light())

```


```{r tidy_data}
# reads saved df
df <- readRDS("data/health.rds") %>% filter(unit == "kg")

# skimr::skim(df)
df <- df %>% 
  mutate(startDate = ymd_hms(stringr::str_sub(startDate, 1, 19))) %>% 
  mutate(year = factor(year(startDate)), month = factor(month(startDate)))
```

## Evolution par mois

```{r plot_mois, include=T}
df %>% 
  ggplot(aes(x = startDate, y = value)) + 
  geom_point(color = "seagreen")  +
  scale_x_datetime(date_breaks = "6 month", date_labels = "%Y %b") +
  theme(axis.text.x = element_text(angle = 90)) -> p

plotly::ggplotly()
```

```{r model_month}
mod_month <- lm(formula = "value ~ month", data = df)
summary(mod_month)
df$pred_month <- predict(mod_month)
df <- df %>%  mutate(res_month = value - pred_month)  
ggplot(df, aes(x = startDate, y = res_month)) +
  geom_point(color = "darkblue") + labs(title = " Résidus modèle mois") +
scale_x_datetime(date_breaks = "6 month", date_labels = "%Y %b") +
  theme(axis.text.x = element_text(angle = 90)) -> p
plotly::ggplotly()
```

```{r model_year}
mod_year <- lm(formula = "value ~ year", data = df)
summary(mod_year)
df$pred_year <- predict(mod_year)
broom::tidy(mod_year)
ggplot(data = df, aes(startDate, pred_year)) + geom_line() + scale_x_datetime(date_breaks = "1 year", date_labels = "%Y")
plotly::ggplotly()
```

